### ISSUE TITLE
Plan a new stack

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/codeshameless#3]

**Comment by simonv3** [comment]
What are your thoughts?

**Comment by RichardLitt** [comment]
I need to learn Node properly - I still haven't managed to make a webapp with it. I'm thinking Node and React. Maybe Meteor, though?

**Comment by simonv3** [comment]
I've been pretty keen to learn about using meteor recently. Dunno why.

**Comment by RichardLitt** [comment]
I'm going to blame @urigo for that.

**Comment by RichardLitt** [comment]
Want to try Meteor with me?

**Comment by simonv3** [comment]
See my comment in #4 I don't know whether we need a 'stack'. Maybe a google or mailchimp form is good enough.

Edit: but then, if you want to learn something new, Meteor is as good as anything really.

**Comment by RichardLitt** [comment]
Moving discussion to #4
